Repository alexandreboucardepitech/FootbAPPe, pull requests merged in 2023-12, with the labels that each got.

#30 feat(guess the player): avoid user to guess two times the same player…
  FootbAPPe/app/games/GuessThePlayerLevel.js
  FootbAPPe/app/games/LevelsList.js
  FootbAPPe/app/games/SearchPlayer.js
Labels: bug, enhancement

#32 feat(positions_colors): change color depending on difference between …
  FootbAPPe/app/games/GuessThePlayerLevel.js
Labels: enhancement

#41 40 send name of the player instead of id for guess player name
  FootbAPPe/app/games/CarrerTracerLevel.js
  FootbAPPe/app/games/GuessThePlayerLevel.js
  FootbAPPe/app/games/LevelsList.js
  FootbAPPe/app/games/SearchPlayer.js
  FootbAPPe/app/games/Starting11Level.js
Labels: bug

#43 38 save data in cache
  FootbAPPe/app/games/GuessThePlayer.js
  FootbAPPe/app/games/GuessThePlayerLevel.js
  FootbAPPe/app/games/SearchPlayer.js
  FootbAPPe/database.py
Labels: enhancement

#48 47 notification system
  FootbAPPe/App.js
  FootbAPPe/android/app/src/main/AndroidManifest.xml
  FootbAPPe/package-lock.json
  FootbAPPe/package.json
Labels: enhancement

#49 45 career tracer game
  FootbAPPe/App.js
  FootbAPPe/app/Credits.js
  FootbAPPe/app/GameMenu.js
  FootbAPPe/app/games/CareerTracer.js
  FootbAPPe/app/games/CareerTracerLevel.js
  FootbAPPe/app/games/CarrerTracerLevel.js
  FootbAPPe/app/games/GuessPlayerNameLevel.js
  FootbAPPe/app/games/GuessThePlayer.js
  FootbAPPe/app/games/GuessThePlayerLevel.js
  FootbAPPe/app/games/LevelsList.js
  FootbAPPe/app/games/SearchPlayer.js
  FootbAPPe/assets/CareerTracer.png
  FootbAPPe/server/.gcloudignore
  FootbAPPe/server/app.yaml
  FootbAPPe/server/database.py
  FootbAPPe/server/requirements.txt
  FootbAPPe/server/server.py
  FootbAPPe/start-ngrok.sh
Labels: enhancement

#52 42 create positions for starting 11
  FootbAPPe/app/games/SearchPlayer.js
  FootbAPPe/app/games/SearchPlayerS11.js
  FootbAPPe/app/games/Starting11.js
  FootbAPPe/app/games/Starting11Level.js
Labels: enhancement

#54 44 coins system
  FootbAPPe/app/DisplayCoins.js
  FootbAPPe/app/GameMenu.js
  FootbAPPe/app/games/GuessThePlayer.js
  FootbAPPe/app/games/GuessThePlayerLevel.js
  FootbAPPe/assets/coin.png
  FootbAPPe/package.json
Labels: enhancement

#55 53 check all levels and if coins and local storage works correctly
  FootbAPPe/app/games/CareerTracer.js
  FootbAPPe/app/games/CareerTracerLevel.js
  FootbAPPe/app/games/GuessPlayerName.js
  FootbAPPe/app/games/GuessPlayerNameLevel.js
  FootbAPPe/app/games/GuessThePlayer.js
  FootbAPPe/app/games/GuessThePlayerLevel.js
  FootbAPPe/app/games/LevelsList.js
  FootbAPPe/app/games/SearchPlayer.js
  FootbAPPe/app/games/SearchPlayerS11.js
  FootbAPPe/app/games/Starting11.js
  FootbAPPe/app/games/Starting11Level.js
  FootbAPPe/package.json
Labels: enhancement
